// Opt-in integration test for our own renderer, in an isolated hidden window.
// It never opens a retailer page, signs in, transfers a basket or purchases.
const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');
async function run({win,cat,app}){
 await fs.unlink(path.join(app.getPath('userData'),'verification.json')).catch(()=>{});
 await fs.unlink(path.join(app.getPath('userData'),'verification-error.txt')).catch(()=>{});
 const report={version:app.getVersion(),packaged:app.isPackaged,checks:[],started:new Date().toISOString()};
 const js=async code=>{try{return await win.webContents.executeJavaScript(code)}catch(e){throw new Error(e.message+'\nVerification step: '+code)}};
 const until=async(condition)=>{const start=Date.now();while(!await js(condition)){if(Date.now()-start>45000)throw new Error('Renderer timeout: '+condition+'\n'+await js('document.body.innerText.slice(0,2000)'));await new Promise(r=>setTimeout(r,100));}};
 await until('Boolean(document.querySelector(".stores-modal")) || Boolean(document.querySelector(".home-feed"))');
 const nw=(await cat.stores('newworld','Broadway')).find(x=>/Palmerston/i.test(x.address));
 const ww=(await cat.stores('woolworths','Kelvin Grove'))[0];assert(nw&&ww);
 const state={version:1,stores:{newworld:nw,woolworths:ww},loyalty:{newworld:true,woolworths:true},basket:[],policy:'cheapest'};
 await js(`window.grocery.save(${JSON.stringify(state)})`);await js("window.grocery.setAppearance('light')");await win.loadURL(win.webContents.getURL());
 await until('!document.querySelector(".stores-modal") && document.querySelector(".store-picker")?.textContent.includes("Broadway")');
 report.checks.push('Store selection persisted through renderer reload');
 await until('document.querySelectorAll(".recommendation-shelf .product-card").length >= 4');
 const shelves=await js('Array.from(document.querySelectorAll(".recommendation-shelf")).map(s=>({name:s.querySelector("h2").textContent,count:s.querySelectorAll(".product-card").length}))');
 assert(shelves.length>=6);assert(shelves.some(s=>s.count===4));assert(shelves.every(s=>s.count<=4));
 const layout=await js('({width:window.innerWidth,overflow:document.documentElement.scrollWidth>window.innerWidth,cards:Array.from(document.querySelectorAll(".recommendation-shelf:first-of-type .product-card")).map(c=>({width:c.getBoundingClientRect().width,x:c.getBoundingClientRect().x,y:c.getBoundingClientRect().y}))})');
 assert(!layout.overflow);assert(layout.cards.every(c=>c.width>=140));report.checks.push({name:'Live themed shelves, four quick-add cards and layout',shelves,layout});
 await new Promise(r=>setTimeout(r,400));await fs.writeFile(path.join(app.getPath('userData'),'browse.png'),(await win.webContents.capturePage()).toPNG());
 await js('document.querySelector(".theme-toggle").click()');await until('document.documentElement.dataset.theme === "dark"');
 await new Promise(r=>setTimeout(r,300));await fs.writeFile(path.join(app.getPath('userData'),'browse-dark.png'),(await win.webContents.capturePage()).toPNG());
 const appearance=await js('window.grocery.appearance()');assert.equal(appearance.theme,'dark');
 const colors=await js('({bg:getComputedStyle(document.body).backgroundColor,text:getComputedStyle(document.body).color,header:document.querySelector(".topbar").getBoundingClientRect().height})');assert.equal(colors.header,64);assert.notEqual(colors.bg,'rgb(255, 255, 255)');
 report.checks.push({name:'Compact layout and persistent dark-mode setting',colors});
 const firstAisle=await js('document.querySelector(".recommendation-shelf").dataset.aisle');
 await js('document.querySelector(".recommendation-shelf .add-button:not(:disabled)").click()');await until('Boolean(document.querySelector(".basket-line"))');
 await until('(async()=> (await window.grocery.preferences()).revision > 0)()');
 await new Promise(r=>setTimeout(r,200));
 const learned=JSON.parse(await fs.readFile(path.join(app.getPath('userData'),'recommendations.json'),'utf8'));assert(learned.aisles[firstAisle]?.value>=4);
 await js('document.querySelector(".basket-line button[aria-label^=Remove]").click()');await until('Boolean(document.querySelector(".basket-empty"))');
 await js('document.querySelector(".recommendation-shelf .see-more").click()');await until('document.querySelectorAll(".product-grid .product-card").length>0');
 assert(await js('document.querySelector(".home-feed").hidden'));await js('document.querySelector(".back-to-browse").click()');await until('!document.querySelector(".home-feed").hidden');
 report.checks.push('Shelf quick-add, see more opens aisle, Browse returns to shelves');
 for(let i=0;i<6;i++){await js(`document.querySelectorAll('.recommendation-shelf')[${i}].scrollIntoView({block:'center'})`);await until(`document.querySelectorAll('.recommendation-shelf')[${i}].querySelectorAll('.product-card').length>0`);}
 report.checks.push('All six shelves load lazily while scrolling');
 win.setSize(1060,800);await new Promise(r=>setTimeout(r,100));assert(await js('document.documentElement.scrollWidth<=window.innerWidth'));win.setSize(1380,920);
 await js('document.querySelector(".shop").scrollTo({top:0})');
 await until('document.querySelectorAll(".department-tabs button").length >= 5');
 await js(`Array.from(document.querySelectorAll('.department-tabs button')).find(b=>b.textContent==='Dairy & eggs').click()`);
 await until('document.querySelectorAll(".aisle-tabs button").length > 2');
 await js(`Array.from(document.querySelectorAll('.aisle-tabs button')).find(b=>b.textContent==='Milk').click()`);
 await until('Boolean(document.querySelector(".product-grid .product-card")) && !document.querySelector(".shop > .loading")');
 await js(`Array.from(document.querySelectorAll('.browse-filters button')).find(b=>b.textContent==='House brands').click()`);
 await until('Array.from(document.querySelectorAll(".browse-filters button")).find(b=>b.textContent==="House brands")?.getAttribute("aria-pressed")==="true"');
 const houseNames=await js(`Array.from(document.querySelectorAll('.product-grid .product-card h3')).map(e=>e.textContent)`);assert(houseNames.length>0&&houseNames.every(n=>/Pams|Woolworths|Value|Macro/.test(n)),houseNames.join(', '));assert(await js('Boolean(document.querySelector(".product-grid .equivalent-badge"))'));
 report.checks.push('Live department browsing and house-brand milk equivalents');
 await js(`Array.from(document.querySelectorAll('.browse-filters button')).find(b=>b.textContent==='House brands').click()`);
 await js(`Array.from(document.querySelectorAll('.aisle-tabs button')).find(b=>b.textContent==='Butter').click()`);
 await until('Boolean(document.querySelector(".product-grid .product-card")) && !document.querySelector(".shop > .loading")');
 const cards=await js(`Array.from(document.querySelectorAll('.product-grid .product-card')).map(c=>({name:c.querySelector('h3').textContent,offers:c.querySelectorAll('.add-button').length}))`);
 assert(cards.length>5);assert.equal(cards[0].offers,2);assert(cards.filter(c=>c.offers===2).length>=5);
 report.checks.push({name:'Live products rendered with paired offers first',cards:cards.length,paired:cards.filter(c=>c.offers===2).length});
 await js(`document.querySelector('.product-grid .similar-button').click()`);await until('document.querySelectorAll(".similar-row").length > 0');
 await js(`document.querySelector('.similar-offers button:not(:disabled)').click()`);await until('Boolean(document.querySelector(".added-message"))');
 await js(`document.querySelector('[aria-label="Close similar items"]').click()`);await until('Boolean(document.querySelector(".basket-line"))');
 await js(`document.querySelector('.basket-line button[aria-label^="Remove"]').click()`);await until('Boolean(document.querySelector(".basket-empty"))');
 report.checks.push('Similar-item suggestions and add-to-basket');
 await js(`document.querySelector('.product-grid .product-card .add-button:not(:disabled)').click()`);
 await until('Boolean(document.querySelector(".basket-line"))');
 await js(`document.querySelector('.stepper button[aria-label^="More"]').click()`);
 await until('document.querySelector(".stepper span")?.textContent === "2"');
 await until('(async()=>{const s=await window.grocery.load();return s.basket.length===1&&s.basket[0].quantity===2})()');
 const saved=await js('window.grocery.load()');assert.equal(saved.basket[0].quantity,2);assert.equal(Object.keys(saved.basket[0].offers).length,2);
 await win.loadURL(win.webContents.getURL());await until('document.querySelector(".stepper span")?.textContent === "2"');
 report.checks.push('Add, increase quantity, IPC save and basket reload');
 const original=saved.basket[0];await js(`window.grocery.matchFeedback(${JSON.stringify(original.offers.newworld)},${JSON.stringify(original.offers.woolworths)},false)`);
 assert.equal((await js(`window.grocery.compare(${JSON.stringify(Object.values(original.offers))})`)).length,2);
 await js(`window.grocery.matchFeedback(${JSON.stringify(original.offers.newworld)},${JSON.stringify(original.offers.woolworths)},true)`);
 assert.equal((await js(`window.grocery.compare(${JSON.stringify(Object.values(original.offers))})`)).length,1);
 report.checks.push('Remembered match corrections change native comparison results');
 await js(`document.querySelector('.checkout').click()`);await until('Boolean(document.querySelector(".checkout-modal"))');
 assert(await js('document.querySelector(".checkout-modal").textContent.includes("Open browser")'));
 await js('document.querySelector(".browser-connect").click()');await until('Boolean(document.querySelector(".browser-setup"))');
 assert(await js('document.querySelector(".browser-setup").textContent.includes("Load unpacked")'));
 await js(`document.querySelector('[aria-label="Close browser setup"]').click()`);
 report.checks.push('Browser checkout and companion setup render without opening a real browser');
 await js(`document.querySelector('[aria-label="Close checkout"]').click()`);
 await js(`document.querySelector('.basket-line button[aria-label^="Remove"]').click()`);await until('Boolean(document.querySelector(".basket-empty"))');
 report.checks.push('Remove returns to empty basket');
 const before=await js('window.grocery.preferences()');assert(before.revision>0);
 await js('document.querySelector(".store-picker").click()');await until('Boolean(document.querySelector(".recommendation-settings"))');
 await js('document.querySelector(".recommendation-settings input").click()');await until('(async()=>!(await window.grocery.preferences()).enabled)()');
 await js('document.querySelector(".recommendation-settings .text-button").click()');await until('document.querySelector(".recommendation-settings .text-button").textContent === "History cleared"');
 const profile=JSON.parse(await fs.readFile(path.join(app.getPath('userData'),'recommendations.json'),'utf8'));assert.equal(Object.keys(profile.products).length,0);assert.equal(profile.enabled,false);
 await js('document.querySelector(".recommendation-settings input").click()');await until('(async()=>(await window.grocery.preferences()).enabled)()');
 assert.equal((await js('window.grocery.appearance()')).theme,'dark');report.checks.push('Local learning persisted; settings opt-out and clear-history work; dark mode survives history reset');
 await fs.writeFile(path.join(app.getPath('userData'),'verification.json'),JSON.stringify(report,null,2));
}
module.exports={run};
