// Local visual/interaction fixture. Never connects to a retailer or persists a real basket.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const model=require('../electron/model.cjs');
const root=path.resolve(__dirname,'../dist');
const p=(retailer,id,name,size,cents,more={})=>({retailer,id:retailer+id,name,brand:name.split(' ')[0],size,barcode:'',image:'',cents,regularCents:cents,member:false,offer:'',unit:'each',min:1,max:10,step:1,unitPrice:'',available:true,restricted:false,storeId:retailer,checkedAt:new Date().toISOString(),url:'',...more});
const pair=(id,name,size,a,b,more={})=>{const nw=p('newworld',id,name,size,a,more),ww=p('woolworths',id,name,size,b,more);return {key:id,product:nw,offers:{newworld:nw,woolworths:ww}}};
const rows=[pair('milk','Anchor Blue Milk','2 L',649,619,{unitPrice:'$3.10 / 1 L'}),pair('bread','Vogel’s Original Mixed Grain Bread','750 g',549,599),pair('eggs','Woodland Free Range Eggs','6 pack',799,749),pair('bananas','Bananas','Loose · per kg',379,349,{brand:'Fresh produce',unit:'kg',min:.1,step:.1,max:5}),pair('butter','Mainland Salted Butter','500 g',849,899),pair('apples','Royal Gala Apples','Loose · per kg',449,399,{brand:'Fresh produce',unit:'kg',min:.1,step:.1,max:5})];
const depts=['Fruit & vegetables','Meat & seafood','Fridge, deli & eggs','Bakery','Pantry','Frozen','Drinks','Household','Health & beauty'].map((name,i)=>({id:String(i),name,children:[{id:String(i),name:i===0?'Fresh fruit':i===2?'Milk & cream':name,sources:{newworld:{path:[]},woolworths:{path:[]}}}]}));
const state={version:1,stores:{newworld:{id:'newworld',name:'Broadway',address:''},woolworths:{id:'woolworths',name:'Kelvin Grove',address:''}},loyalty:{newworld:true,woolworths:true},basket:[],policy:'cheapest'};
const fixture=`const rows=${JSON.stringify(rows)},departments=${JSON.stringify(depts)};let state=JSON.parse(sessionStorage.getItem('ui-fixture')||'null')||${JSON.stringify(state)};window.grocery={load:async()=>state,save:async s=>{state=s;sessionStorage.setItem('ui-fixture',JSON.stringify(s));return true},appearance:async()=>({theme:'light'}),setAppearance:async()=>true,onStoreStatus:()=>()=>{},departments:async()=>departments,feedPlan:async()=>departments.slice(0,3).map(d=>d.children[0]),shelf:async id=>({rows:id==='0'?rows.filter(r=>r.product.unit==='kg'):id==='1'?rows.slice(0,3):rows.slice(2,5),partial:false}),compare:async ps=>rows.filter(r=>ps.some(p=>Object.values(r.offers).some(o=>o.id===p.id))),search:async(r,s,q)=>({products:rows.filter(x=>!q||x.product.name.toLowerCase().includes(q.toLowerCase())).map(x=>x.offers[r]),pages:1,total:rows.length}),track:async()=>true,preferences:async()=>({enabled:true,revision:1}),setPersonalisation:async()=>true,resetPreferences:async()=>true,stores:async r=>[state.stores[r]],similar:async()=>({rows,partial:false}),matchCandidates:async()=>[],matchFeedback:async()=>true,browserStatus:async()=>({connected:false,paired:false}),exportList:async()=>true};document.title='Grocery Compare · UI test fixtures';`;
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/fixture.js'){res.setHeader('Content-Type','text/javascript');return res.end(fixture)}const file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.statusCode=404;return res.end('Not found')}let content=fs.readFileSync(file);res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');if(file.endsWith('.html'))content=content.toString().replace('<script type="module"','<script src="/fixture.js"></script><script type="module"');res.end(content)});
server.listen(5178,'127.0.0.1',()=>console.log('UI fixtures http://127.0.0.1:5178'));
