import React,{useEffect,useState} from 'react';
import {Check,ExternalLink,FolderOpen,X} from 'lucide-react';
export function BrowserSetup({onClose}:{onClose:()=>void}){
 const [status,setStatus]=useState({connected:false,paired:false,error:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;const check=()=>window.grocery.browserStatus().then(s=>{if(active)setStatus(s)}).catch(()=>{});check();const timer=setInterval(check,2000);return()=>{active=false;clearInterval(timer)}},[]);
 const action=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}};
 return <div className="modal-backdrop"><section className="modal browser-setup" role="dialog" aria-modal="true" aria-labelledby="browser-setup-title"><div className="modal-heading"><h2 id="browser-setup-title">Your browser companion</h2><button className="icon-button" aria-label="Close browser setup" onClick={onClose}><X size={19}/></button></div>
 {status.connected?<><div className="connection-ready"><Check size={20}/>Browser connected</div><p>Enable your stores from the companion’s toolbar icon, then open each store and sign in. Return here to send your items.</p><p className="muted">Connected confirms the app link. Your retailer login and payment stay on the store’s website.</p></>:<><p>{status.paired?'Your browser is paired but not responding. Open it and resume the companion from its toolbar icon, or reconnect below.':'A one-time setup for Chrome or Edge. Other browsers have not been verified.'}</p><ol className="browser-steps"><li><strong>Load the companion.</strong> Open the folder below. In <code>chrome://extensions</code> or <code>edge://extensions</code>, enable Developer mode → Load unpacked → choose that folder.</li><li><strong>Choose your stores.</strong> Pin the Grocery Compare toolbar icon, open it, and enable the retailers you use.</li><li><strong>Connect.</strong> Use the button below in the same browser profile, then sign in to your stores as usual.</li></ol></>}
 <div className="browser-setup-actions"><button disabled={busy} onClick={()=>action(()=>window.grocery.extensionFolder())}><FolderOpen size={16}/>Companion folder</button>{!status.connected&&<button disabled={busy} className="primary" onClick={()=>action(()=>window.grocery.connectBrowser())}>{status.paired?'Reconnect browser':'Connect browser'}<ExternalLink size={15}/></button>}{status.paired&&<button disabled={busy} className="text-button" onClick={()=>action(async()=>{await window.grocery.disconnectBrowser();setStatus({connected:false,paired:false,error:''})})}>Disconnect</button>}</div>
 <details><summary>Updating an existing companion?</summary><p>After updating the app, click Reload for Grocery Compare on your browser’s Extensions page. If you installed from another folder, replace that entry with the new companion folder. Keep only one copy enabled. The companion’s Setup & help page has troubleshooting steps.</p></details>
 {(error||status.error)&&<p className="error-text" role="alert">{error||status.error}</p>}</section></div>;
}
