import React,{useEffect,useState} from 'react';
import {ArrowRight,ExternalLink,X} from 'lucide-react';
import type {Retailer,State} from './types';
import model from '../electron/model.cjs';
export function Checkout({state,sending,onClose,onOpen,onSend,onConnect}:{state:State;sending:Retailer|null;onClose:()=>void;onOpen:(r:Retailer)=>void;onSend:(r:Retailer)=>void;onConnect:()=>void}){
 const [connected,setConnected]=useState(false);const summary=model.basketSummary(state.basket,state.policy,state.loyalty);
 useEffect(()=>{let active=true;const check=()=>window.grocery.browserStatus().then(s=>{if(active)setConnected(s.connected)}).catch(()=>{});check();const timer=setInterval(check,2000);return()=>{active=false;clearInterval(timer)}},[]);
 return <div className="modal-backdrop"><section className="modal checkout-modal"><div className="modal-heading"><h2>Finish your shop</h2><button className="icon-button" aria-label="Close checkout" onClick={onClose}><X size={19}/></button></div><p className="checkout-note">Sign in in your browser, then send your items. Complete payment at the store.</p><div className={'connection-pill '+(connected?'ready':'')}>{connected?'Browser connected':'Browser companion needed for sending'}</div>{(['newworld','woolworths']as Retailer[]).filter(r=>summary.shops[r].length).map(r=><div className="checkout-store" key={r}><div className="checkout-store-heading"><span className={'store-badge '+r}>{r==='newworld'?'NW':'W'}</span><div><h3>{r==='newworld'?'New World':'Woolworths'}</h3><span>{state.stores[r]?.name} · {summary.shops[r].length} items</span></div></div><div className="checkout-actions"><button onClick={()=>onOpen(r)}>Open browser<ExternalLink size={14}/></button><button className="primary" disabled={!!sending} onClick={()=>connected?onSend(r):onConnect()}>{sending===r?'Sending…':connected?'Send items':'Connect browser'}<ArrowRight size={15}/></button></div></div>)}<button className="text-button browser-connect" onClick={onConnect}>{connected?'Browser settings':'Set up browser companion'}</button></section></div>;
}
