import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,RefreshCw,X} from 'lucide-react';
import type {Aisle,Row,State} from './types';
function Shelf({aisle,stores,onChoose,renderCard,onHide}:{aisle:Aisle;stores:State['stores'];onChoose:(a:Aisle)=>void;renderCard:(r:Row,aisleId?:string)=>React.ReactNode;onHide:()=>void}){
 const ref=useRef<HTMLElement>(null),[visible,setVisible]=useState(false),[rows,setRows]=useState<Row[]|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[partial,setPartial]=useState(false);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setVisible(true);observer.disconnect()}},{rootMargin:'180px'});if(ref.current)observer.observe(ref.current);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!visible)return;let cancelled=false;setError('');window.grocery.shelf(aisle.id,stores).then(result=>{if(!cancelled){setRows(result.rows);setPartial(result.partial)}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[visible,aisle.id,retry,stores.newworld?.id,stores.woolworths?.id]);
 useEffect(()=>{if(!rows?.length)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.intersectionRatio>=0.25)){window.grocery.track({type:'impression',products:rows.slice(0,4).map(r=>r.product),aisle:aisle.id}).catch(()=>{});observer.disconnect()}},{threshold:0.25});if(ref.current)observer.observe(ref.current);return()=>observer.disconnect()},[rows,aisle.id]);
 return <section ref={ref} className="recommendation-shelf" data-aisle={aisle.id}><header><button className="shelf-title" onClick={()=>onChoose(aisle)}><h2>{aisle.name}</h2></button><div><button className="see-more" onClick={()=>onChoose(aisle)}>See more<ArrowRight size={15}/></button><button className="icon-button" aria-label={`Hide ${aisle.name} shelf`} onClick={onHide}><X size={14}/></button></div></header>
 {error?<div className="shelf-error">{error}<button onClick={()=>setRetry(v=>v+1)}>Retry</button></div>:rows?<><div className="shelf-products">{rows.slice(0,4).map(r=><React.Fragment key={r.key}>{renderCard(r,aisle.id)}</React.Fragment>)}</div>{!rows.length&&<button className="quiet" onClick={()=>onChoose(aisle)}>Explore this aisle<ArrowRight size={15}/></button>}{partial&&<small className="partial-shelf">One store is unavailable</small>}</>:<div className="shelf-skeleton" aria-label={`Loading ${aisle.name}`}>{[0,1,2,3].map(i=><div key={i}/>)}</div>}</section>;
}
export function HomeFeed({state,hidden,epoch,onChoose,renderCard}:{state:State;hidden:boolean;epoch:number;onChoose:(a:Aisle)=>void;renderCard:(r:Row,aisleId?:string)=>React.ReactNode}){
 const [plan,setPlan]=useState<Aisle[]>([]),[limit,setLimit]=useState(3),[refresh,setRefresh]=useState(0),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;setError('');window.grocery.feedPlan(state.stores).then(p=>{if(!cancelled)setPlan(p)}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[state.stores.newworld?.id,state.stores.woolworths?.id,epoch,refresh]);
 return <div className="home-feed" hidden={hidden}>{error&&<div className="shelf-error">{error}<button onClick={()=>setRefresh(v=>v+1)}>Retry</button></div>}{!plan.length&&!error&&<div className="loading"><RefreshCw className="spin"/>Loading your shelves…</div>}
 {plan.slice(0,limit).map(a=><Shelf key={a.id+'-'+epoch+'-'+refresh+'-'+state.stores.newworld?.id+'-'+state.stores.woolworths?.id} aisle={a} stores={state.stores} onChoose={onChoose} renderCard={renderCard} onHide={()=>{window.grocery.track({type:'dismiss',aisle:a.id}).catch(()=>{});setPlan(p=>p.filter(s=>s.id!==a.id))}}/>)}{limit<plan.length&&<button className="more" onClick={()=>setLimit(v=>v+4)}>More aisles</button>}</div>;
}
