import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ShoppingBasket,Search,MapPin,ChevronDown,Plus,Minus,X,ArrowLeft,ArrowRight,RefreshCw,Check,ShoppingBag,Download,SlidersHorizontal,Store as StoreIcon} from 'lucide-react';
import model from '../electron/model.cjs';
import type {State,Retailer,Policy,Store,Product,Row,Line} from './types';
import './style.css';
const {groupProducts,effectivePrice,basketSummary}=model;
const names={newworld:'New World',woolworths:'Woolworths'};
const retailers:Retailer[]=['newworld','woolworths'];
const dollars=(c:number|null)=>c===null?'—':new Intl.NumberFormat('en-NZ',{style:'currency',currency:'NZD'}).format(c/100);
const empty:State={version:1,stores:{newworld:null,woolworths:null},loyalty:{newworld:true,woolworths:true},basket:[],policy:'cheapest'};
function Badge({r}:{r:Retailer}){return <span className={'store-badge '+r}>{r==='newworld'?'NW':'W'}</span>}
function Picture({p}:{p:Product}){const [failed,setFailed]=useState(false);return <div className="picture">{!failed&&p.image?<img src={p.image} alt="" loading="lazy" onError={()=>setFailed(true)}/>:<ShoppingBag size={34}/>}</div>}
function App(){
 const [state,setState]=useState<State>(empty),[loaded,setLoaded]=useState(false),[query,setQuery]=useState(''),[searched,setSearched]=useState('');
 const [rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[errors,setErrors]=useState<Partial<Record<Retailer,string>>>({});
 const [pages,setPages]=useState<Record<Retailer,number>>({newworld:0,woolworths:0}),[hasMore,setHasMore]=useState(false);
 const [storeModal,setStoreModal]=useState(false),[match,setMatch]=useState<Row|null>(null),[checkout,setCheckout]=useState(false);
 const [browser,setBrowser]=useState<{retailer:Retailer|null;url:string;loading:boolean}>({retailer:null,url:'',loading:false});
 const [notice,setNotice]=useState(''),[sort,setSort]=useState('relevance'),[filter,setFilter]=useState<Policy>('cheapest');
 const [refreshing,setRefreshing]=useState(false),[sending,setSending]=useState<Retailer|null>(null);
 const [,setClock]=useState(0);
 const requestId=useRef(0),lastProducts=useRef<Product[]>([]),stateRef=useRef(state),saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 stateRef.current=state;
 useEffect(()=>{window.grocery.load().then(s=>{setState(s);setLoaded(true);if(!s.stores.newworld||!s.stores.woolworths)setStoreModal(true)}).catch(e=>setNotice(e.message));return window.grocery.onStoreStatus(setBrowser)},[]);
 useEffect(()=>{if(!loaded)return;window.grocery.save(state).catch(e=>setNotice('Could not save your basket: '+e.message));},[state,loaded]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),8000);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{const t=setInterval(()=>setClock(c=>c+1),60000);return()=>clearInterval(t)},[]);
 const ready=retailers.every(r=>state.stores[r]);
 async function search(q=query,more=false){
  q=q.trim();if(!q)return;if(!ready){setStoreModal(true);return;}
  const id=++requestId.current;setBusy(true);setErrors({});setSearched(q);setQuery(q);
  if(!more){lastProducts.current=[];setRows([]);setPages({newworld:0,woolworths:0});}
  const nextPages={newworld:more?pages.newworld+1:0,woolworths:more?pages.woolworths+1:0};
  const results=await Promise.allSettled(retailers.map(r=>window.grocery.search(r,state.stores[r]!,q,nextPages[r])));
  if(id!==requestId.current)return;
  const products:Product[]=more?[...lastProducts.current]:[];const errs:Partial<Record<Retailer,string>>={};let moreAvailable=false;
  results.forEach((result,i)=>{const r=retailers[i];if(result.status==='fulfilled'){products.push(...result.value.products);moreAvailable||=result.value.pages>nextPages[r]+1;}else errs[r]=result.reason.message;});
  const unique=[...new Map(products.map(p=>[p.retailer+':'+p.id,p])).values()];lastProducts.current=unique;
  setRows(groupProducts(unique) as Row[]);setErrors(errs);setPages(nextPages);setHasMore(moreAvailable);setBusy(false);
 }
 function add(row:Row,r?:Retailer){const p=r?row.offers[r]:row.product;if(!p||!p.available)return;
  setState(s=>{const old=s.basket.find(l=>Object.values(l.offers).some(o=>o?.id===p.id&&o.retailer===p.retailer));return {...s,basket:old?s.basket.map(l=>l===old?{...l,quantity:Math.min(p.max,Math.round((l.quantity+p.step)*1000)/1000)}:l):[...s.basket,{...row,quantity:p.min,preferred:r||'cheapest'}]};});
 }
 function changeQty(key:string,delta:number){setState(s=>({...s,basket:s.basket.map(l=>l.key===key?{...l,quantity:Math.round((l.quantity+delta)*1000)/1000}:l).filter(l=>l.quantity>0)}))}
 async function refreshBasket(){
  if(!ready)return;setRefreshing(true);const snapshot=stateRef.current;let failures=0;
  const updated:Line[]=[];
  for(const line of snapshot.basket){const offers:Row['offers']={};
   for(const r of retailers){const previous=line.offers[r];if(!previous)continue;
    try{const data=await window.grocery.search(r,snapshot.stores[r]!,[previous.brand,previous.name.replace(previous.brand,'').replace(previous.size,'')].join(' ').trim().slice(0,100),0,true);let p=data.products.find(p=>p.id===previous.id);if(!p)p=data.products.find(p=>p.name.toLowerCase()===previous.name.toLowerCase()&&p.unit===previous.unit);if(p)offers[r]=p;else failures++;}catch{offers[r]={...previous,checkedAt:'1970-01-01T00:00:00Z'};failures++;}
   }
   updated.push({...line,offers,product:Object.values(offers)[0]||line.product});
  }
  setState(s=>retailers.some(r=>s.stores[r]?.id!==snapshot.stores[r]?.id)?s:({...s,basket:s.basket.map(l=>{const u=updated.find(x=>x.key===l.key);return u?{...u,quantity:l.quantity,preferred:l.preferred}:l})}));setRefreshing(false);if(failures)setNotice(`${failures} price(s) unavailable. Choose another item or try again.`);
 }
 async function openStore(r:Retailer){await window.grocery.save(stateRef.current);try{await window.grocery.openStore(r);setBrowser(b=>({...b,retailer:r}));}catch(e){setNotice((e as Error).message)}}
 async function send(r:Retailer){setSending(r);try{await window.grocery.save(stateRef.current);const result=await window.grocery.transfer(r);setNotice(`${result.count} items verified in ${names[r]}.${result.messages.length?' '+result.messages.join(' '):''}`);}catch(e){setNotice((e as Error).message)}finally{setSending(null)}}
 const summary=basketSummary(state.basket,state.policy,state.loyalty);
 const choices:Policy[]=['newworld','woolworths','cheapest'];
 const shown=rows.filter(row=>filter==='cheapest'||row.offers[filter]).sort((a,b)=>{if(sort==='relevance')return 0;const price=(r:Row)=>Math.min(...Object.values(r.offers).map(p=>effectivePrice(p,state.loyalty[p!.retailer])??Infinity));return sort==='low'?price(a)-price(b):a.product.name.localeCompare(b.product.name)});
 const stale=state.basket.some(l=>Object.values(l.offers).some(p=>p?.storeId!==state.stores[p!.retailer]?.id||Date.now()-Date.parse(p!.checkedAt)>30*60*1000));
 if(browser.retailer)return <div className="store-shell"><header className="browser-bar"><button className="back" onClick={async()=>{await window.grocery.closeStore();setBrowser({retailer:null,url:'',loading:false})}}><ArrowLeft size={18}/> Back to basket</button><Badge r={browser.retailer}/><strong>{names[browser.retailer]}</strong><span className="browser-address">{(()=>{try{return new URL(browser.url).hostname}catch{return 'Loading…'}})()}</span><button className="icon-button" aria-label="Reload store" onClick={()=>window.grocery.navigate('reload')}><RefreshCw size={18} className={browser.loading?'spin':''}/></button><button onClick={()=>window.grocery.navigate('cart')}>Store cart</button></header>{notice&&<div className="toast browser-toast">{notice}</div>}</div>;
 return <div className="app"><header className="topbar"><div className="brand"><span className="brand-icon"><ShoppingBasket size={24}/></span><span>Grocery Compare</span></div><div className="stores">{retailers.map(r=><button key={r} className="store-picker" onClick={()=>setStoreModal(true)}><Badge r={r}/><span>{state.stores[r]?.name||'Choose store'}</span><ChevronDown size={14}/></button>)}</div></header>
 <div className="workspace"><main className="shop"><div className="shop-heading"><h1>Your weekly shop.</h1><button className="quiet" onClick={()=>setStoreModal(true)}><SlidersHorizontal size={17}/> Stores</button></div>
 <form className="search" onSubmit={e=>{e.preventDefault();search()}}><Search size={23}/><input aria-label="Search groceries" placeholder="Search your groceries" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/>{query&&<button type="button" className="icon-button" aria-label="Clear search" onClick={()=>setQuery('')}><X size={17}/></button>}<button className="primary" type="submit" disabled={busy}>Search</button></form>
 <div className="quick-searches">{['Milk','Bread','Eggs','Butter','Chicken','Fruit','Coffee'].map(q=><button key={q} className={searched.toLowerCase()===q.toLowerCase()?'active':''} onClick={()=>search(q)}>{q}</button>)}</div>
 {searched&&<div className="result-toolbar"><div className="tabs">{(['cheapest',...retailers] as Policy[]).map(r=><button key={r} className={filter===r?'selected':''} onClick={()=>setFilter(r)}>{r==='cheapest'?'Both stores':names[r]}</button>)}</div><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="relevance">Relevance</option><option value="low">Lowest price</option><option value="name">A to Z</option></select></div>}
 {retailers.map(r=>errors[r]&&<div className="inline-error" key={r}><Badge r={r}/><span>{errors[r]}</span><button onClick={()=>openStore(r)}>Open store</button></div>)}
 {!searched?<div className="welcome"><div className="welcome-art"><ShoppingBasket size={62} strokeWidth={1.3}/><span className="price-token left">$</span><span className="price-token right"><Check size={19}/></span></div><h2>Two stores. One basket.</h2><p>Search to start your shop.</p></div>:<>
 <div className="product-grid">{shown.map(row=><article className="product-card" key={row.key}><Picture p={row.product}/><div className="product-name"><span>{row.product.brand||'GROCERIES'}</span><h3>{row.product.name}</h3></div><div className="offer-list">{retailers.map(r=>{const p=row.offers[r];const c=p?effectivePrice(p,state.loyalty[r]):null;return <div className={'offer '+(!p?'missing':'')} key={r}><Badge r={r}/><div className="offer-price">{p?<><strong>{dollars(c)}{p.unit==='kg'&&<small> / kg</small>}</strong><span>{p.member?'Member price':p.unitPrice||'Each'}</span></>:<button className="find-match" onClick={()=>setMatch(row)}>Find match</button>}</div>{p&&<button className="add-button" aria-label={`Add ${p.name} from ${names[r]}`} disabled={!p.available||p.restricted||c===null} onClick={()=>add(row,r)}>{p.restricted?'18+':!p.available?'—':<Plus size={19}/>}</button>}</div>})}</div></article>)}</div>
 {busy&&<div className="loading"><RefreshCw size={21} className="spin"/> Finding your groceries…</div>}{!busy&&!shown.length&&!Object.keys(errors).length&&<div className="welcome"><Search size={42}/><h2>No products found</h2><p>Try a shorter search.</p></div>}{hasMore&&!busy&&<button className="more" onClick={()=>search(searched,true)}>Show more</button>}</>}
 </main><aside className="basket"><div className="basket-heading"><div><h2>Your basket <span>{state.basket.length}</span></h2></div><button className="icon-button" aria-label="Export shopping list" disabled={!state.basket.length} onClick={()=>window.grocery.exportList().catch(e=>setNotice(e.message))}><Download size={18}/></button></div>
 {!state.basket.length?<div className="basket-empty"><ShoppingBag size={34} strokeWidth={1.4}/><p>Your basket is empty</p></div>:<><div className="basket-lines">{state.basket.map(line=>{const offer=model.selectOffer(line,state.policy,state.loyalty) as Product|null;return <div className="basket-line" key={line.key}><Picture p={line.product}/><div className="line-body"><div className="line-title"><h3>{line.product.name}</h3><button className="icon-button" aria-label={`Remove ${line.product.name}`} onClick={()=>setState(s=>({...s,basket:s.basket.filter(l=>l.key!==line.key)}))}><X size={14}/></button></div><div className="line-store"><select aria-label={`Store for ${line.product.name}`} value={line.preferred} onChange={e=>setState(s=>({...s,basket:s.basket.map(l=>l.key===line.key?{...l,preferred:e.target.value as Policy}:l)}))}><option value="cheapest">Cheapest</option>{retailers.filter(r=>line.offers[r]).map(r=><option value={r} key={r}>{names[r]}</option>)}</select><button className="text-button" onClick={()=>setMatch(line)}>Compare</button></div><div className="line-bottom"><div className="stepper"><button aria-label={`Less ${line.product.name}`} onClick={()=>changeQty(line.key,-line.product.step)}><Minus size={13}/></button><span>{line.quantity}{line.product.unit==='kg'?' kg':''}</span><button aria-label={`More ${line.product.name}`} disabled={line.quantity+line.product.step>line.product.max} onClick={()=>changeQty(line.key,line.product.step)}><Plus size={13}/></button></div><strong>{offer?dollars(Math.round(effectivePrice(offer,state.loyalty[offer.retailer])!*line.quantity)):'Unavailable'}</strong></div></div></div>})}</div>
 <div className="basket-bottom"><div className="plan-label"><span>Where to shop</span><button className="text-button" onClick={()=>refreshBasket()} disabled={refreshing}><RefreshCw size={13} className={refreshing?'spin':''}/> Refresh</button></div><div className="plans">{choices.map(p=>{const total=basketSummary(state.basket,p,state.loyalty);return <button key={p} className={'plan '+(state.policy===p?'chosen':'')} onClick={()=>setState(s=>({...s,policy:p}))}><span>{p==='cheapest'?'Split shop':names[p]}</span><strong>{dollars(total.cents)}</strong>{total.missing>0&&<small>{total.missing} missing</small>}</button>})}</div>{stale&&<div className="stale">Prices need refreshing <button onClick={()=>refreshBasket()} disabled={refreshing}>Refresh</button></div>}<div className="total"><span>Subtotal</span><strong>{dollars(summary.cents)}</strong></div><div className="subtotal-note">{summary.missing?`${summary.missing} items unavailable · `:''}Before delivery and bag fees</div><button className="primary checkout" disabled={refreshing||stale||summary.missing>0} onClick={()=>setCheckout(true)}>Continue to stores <ArrowRight size={17}/></button></div></>}
 </aside></div>
 {storeModal&&<StoreModal state={state} onClose={()=>setStoreModal(false)} onSave={stores=>{requestId.current++;setState(s=>({...s,stores}));setStoreModal(false);setRows([]);setSearched('');lastProducts.current=[];setBusy(false);}} onLoyalty={(r,value)=>setState(s=>({...s,loyalty:{...s.loyalty,[r]:value}}))}/>}
 {match&&<MatchModal row={match} state={state} onClose={()=>setMatch(null)} onChoose={p=>{const update=(row:Row)=>({...row,offers:{...row.offers,[p.retailer]:p}});setRows(rs=>rs.map(r=>r.key===match.key?update(r):r));setState(s=>({...s,basket:s.basket.map(l=>l.key===match.key?{...l,...update(l)}:l)}));setMatch(null)}}/>}
 {checkout&&<div className="modal-backdrop"><div className="modal checkout-modal"><div className="modal-heading"><h2>Finish your shop</h2><button className="icon-button" aria-label="Close checkout" onClick={()=>setCheckout(false)}><X/></button></div><p className="checkout-note">Sign in at each store, then send your items. Sending again sets the same quantities.</p>{retailers.filter(r=>summary.shops[r].length).map(r=><div className="checkout-store" key={r}><div className="checkout-store-heading"><Badge r={r}/><div><h3>{names[r]}</h3><span>{state.stores[r]?.name} · {summary.shops[r].length} items</span></div></div><div className="checkout-actions"><button onClick={()=>openStore(r)}>Open store</button><button className="primary" disabled={!!sending} onClick={()=>send(r)}>{sending===r?'Sending…':'Send items'}<ArrowRight size={16}/></button></div></div>)}</div></div>}
 {notice&&<div role="status" className="toast">{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 </div>
}
function StoreModal({state,onClose,onSave,onLoyalty}:{state:State;onClose:()=>void;onSave:(s:State['stores'])=>void;onLoyalty:(r:Retailer,v:boolean)=>void}){
 const [selected,setSelected]=useState(state.stores),[q,setQ]=useState(''),[results,setResults]=useState<Record<Retailer,Store[]>>({newworld:[],woolworths:[]}),[loading,setLoading]=useState(false),[error,setError]=useState('');const seq=useRef(0);
 useEffect(()=>{const id=++seq.current;const t=setTimeout(async()=>{setLoading(true);const data=await Promise.allSettled(retailers.map(r=>window.grocery.stores(r,q)));if(seq.current!==id)return;setError('');data.forEach((d,i)=>{if(d.status==='fulfilled')setResults(s=>({...s,[retailers[i]]:d.value}));else setError(d.reason.message)});setLoading(false)},300);return()=>clearTimeout(t)},[q]);
 return <div className="modal-backdrop"><div className="modal stores-modal"><div className="modal-heading"><h2>Your stores</h2><button className="icon-button" aria-label="Close store settings" onClick={onClose}><X/></button></div><div className="store-search"><MapPin size={18}/><input aria-label="Find stores" placeholder="Town, suburb or store name" value={q} onChange={e=>setQ(e.target.value)}/>{loading&&<RefreshCw size={17} className="spin"/>}</div>{error&&<p className="error-text">{error}</p>}<div className="store-columns">{retailers.map(r=><section key={r}><h3><Badge r={r}/>{names[r]}</h3><div className="store-options">{results[r].map(s=><button key={s.id} className={selected[r]?.id===s.id?'selected':''} onClick={()=>setSelected(v=>({...v,[r]:s}))}><span>{s.name}<small>{s.address}</small></span>{selected[r]?.id===s.id&&<Check size={17}/>}</button>)}{!loading&&!results[r].length&&<p>No stores found</p>}</div><label className="loyalty"><input type="checkbox" checked={state.loyalty[r]} onChange={e=>onLoyalty(r,e.target.checked)}/>{r==='newworld'?'Clubcard prices':'Everyday Rewards prices'}</label></section>)}</div><div className="modal-footer"><span>{retailers.map(r=>selected[r]?.name).filter(Boolean).join(' + ')}</span><button className="primary" disabled={!selected.newworld||!selected.woolworths} onClick={()=>onSave(selected)}>Save stores</button></div></div></div>
}
function MatchModal({row,state,onClose,onChoose}:{row:Row;state:State;onClose:()=>void;onChoose:(p:Product)=>void}){
 const r:Retailer=row.offers.newworld&&!row.offers.woolworths?'woolworths':row.offers.woolworths&&!row.offers.newworld?'newworld':row.product.retailer==='newworld'?'woolworths':'newworld';
 const [query,setQuery]=useState(row.product.name),[results,setResults]=useState<Product[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const seq=useRef(0);
 async function find(){const id=++seq.current;setBusy(true);setError('');try{const d=await window.grocery.search(r,state.stores[r]!,query.slice(0,100));if(id===seq.current)setResults(d.products)}catch(e){setError((e as Error).message)}finally{if(id===seq.current)setBusy(false)}}
 useEffect(()=>{find()},[]);
 return <div className="modal-backdrop"><div className="modal match-modal"><div className="modal-heading"><h2>Choose an equivalent</h2><button className="icon-button" aria-label="Close matching" onClick={onClose}><X/></button></div><p className="match-source">{row.product.name}</p><form className="search compact" onSubmit={e=>{e.preventDefault();find()}}><Search size={18}/><input aria-label="Search equivalent product" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/><button className="primary" disabled={busy}>Search</button></form><h3 className="match-store"><Badge r={r}/>{names[r]}</h3><div className="match-results">{busy?<div className="loading"><RefreshCw className="spin"/>Searching…</div>:results.filter(p=>p.unit===row.product.unit&&!p.restricted).map(p=><button className="match-result" key={p.id} onClick={()=>onChoose(p)}><Picture p={p}/><span>{p.name}<small>{p.unitPrice}</small></span><strong>{dollars(effectivePrice(p,state.loyalty[r]))}</strong><Plus size={18}/></button>)}{!busy&&!results.length&&<p>{error||'No matches. Try fewer words.'}</p>}</div></div></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
